# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e556bcaee676c6d595a67e09980ed36be6b7d0e7f79fd64cfed9c5a81d7de71b44835dc8cf10a1acd631033e5b01da9e5eebb2a99c6f37dc50bcbb6f5026e8a9

test:
  secret_key_base: bd0d56f610ad639cfa52592381bd0103ad1fe524fba13c1c199ac615186be09dee8b0b3176726f4853897e34efaedd4d85ce81316c2475f6070a43cb20cb1da2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
